// samples/react/src/App.jsx
import React from "react";
import "./App.css";
import { BrowserRouter as Router, Route } from "react-router-dom";
import Home from './components/_home';
import TwicBasicGrid from './components/twicBasicGrid';
import TwicSlideshow from './components/twicSlideshow';
import TwicSlider from './components/twicSlider';
import TwicStyleDriven from "./components/twicStyleDriven";
import TwicResponsiveDesign from "./components/twicResponsiveDesign";
import TwicFocus from "./components/twicFocus";
import TwicMode from "./components/twicMode";
import TwicPlaceholder from "./components/twicPlaceholder";
import TwicPosition from "./components/twicPosition";
import TwicTransition from "./components/twicTransition";
import TwicRatio from "./components/twicRatio";
import TwicFlipCard from "./components/twicFlipCard";
import TwicModal from "./components/twicModal";
import TwicLifeCycle from "./components/twicLifeCycle";

function App() {
    return (
        <div className="App">
            <Router>
                <>
                    <Route exact path="/" component={Home} />
                    <Route exact path="/basic-grid" component={TwicBasicGrid} />
                    <Route exact path="/flip" component={TwicFlipCard} />
                    <Route exact path="/focus" component={TwicFocus} />
                    <Route exact path="/life-cycle" component={TwicLifeCycle} />
                    <Route exact path="/modal" component={TwicModal} />
                    <Route exact path="/mode" component={TwicMode} />
                    <Route exact path="/positions" component={TwicPosition} />
                    <Route exact path="/placeholders" component={TwicPlaceholder} />
                    <Route exact path="/ratio" component={TwicRatio} />
                    <Route exact path="/slider" component={TwicSlider} />
                    <Route exact path="/slideshow" component={TwicSlideshow} />
                    <Route exact path="/style-driven" component={TwicStyleDriven} />
                    <Route exact path="/transition" component={TwicTransition} />
                    <Route exact path="/responsive-design" component={TwicResponsiveDesign} />
                </>
            </Router>
        </div>
    );
}
export default App;

// samples/svelte/src/App.svelte
<script>
  import router from "page";
  import Home from "./components/Home.svelte";
  import ArtDirections from './components/TwicArtDirections.svelte';
  import BasicGrid from './components/TwicBasicGrid.svelte';
  import FlipCards from './components/TwicFlipCards.svelte';
  import Focus from './components/TwicFocus.svelte';
  import GridAndZoom from './components/TwicGridAndZoom.svelte';
  import Modal from './components/twic-modal/TwicModal.svelte';
  import Mode from './components/TwicMode.svelte';
  import Placeholder from './components/TwicPlaceholder.svelte';
  import Position from './components/TwicPosition.svelte';
  import PreTransform from './components/TwicPreTransform.svelte';
  import Ratio from './components/TwicRatio.svelte';
  import Slider from './components/TwicSlider.svelte';
  import Slideshow from './components/twic-slideshow/TwicSlideshow.svelte';
  import StyleDriven from './components/TwicStyleDriven.svelte';
  import PageTemplating from './components/TwicPageTemplating.svelte';
  import Transition from './components/TwicTransition.svelte';

  let page;

  router('/', () => page = Home);
  router('/art-directions', () => page = ArtDirections);
  router('/basic-grid', () => page = BasicGrid);
  router('/flip-cards', () => page = FlipCards);
  router('/focus', () => page = Focus);
  router('/grid-and-zoom', () => page = GridAndZoom);
  router('/modal', () => page = Modal);
  router('/mode', () => page = Mode);
  router('/placeholder', () => page = Placeholder);
  router('/position', () => page = Position);
  router('/pretransform', () => page = PreTransform);
  router('/ratio', () => page = Ratio);
  router('/slider', () => page = Slider);
  router('/slideshow', () => page = Slideshow);
  router('/style-driven', () => page = StyleDriven);
  router('/transition', () => page = Transition);
  router('/page-templating', () => page = PageTemplating);

  router.start();
</script>

<svelte:component this={page} />

<style lang="scss">
</style>
