// samples/svelte/src/components/TwicStyleDriven.svelte
<script>
import { TwicWrapper, TwicAbstract } from "@twicpics/components-demo-wrapper/svelte";
import { TwicImg } from "@twicpics/components/svelte3";

const imgUrl = `components/horse.jpg`;
</script>

<TwicWrapper>
  <div class="twic-style-driven-container">
    <TwicAbstract
      title="CSS style driven"
      codeSandBoxUrl="https://codesandbox.io/s/twicpics-x-svelte-styles-driven-ww3yjn"
      codeSandBoxName="TwicPics x Svelte - CSS style driven"
    >
      <p>
        You can set up the TwicPics components using pure CSS and the power of
        CSS variables.
      </p>
    </TwicAbstract>
    <h2>1. Display ratio with <span class="twic-code">--twic-ratio</span></h2>
    <div class="twic-grid">
      <div class="twic-item landscape">
        <TwicImg src={ imgUrl }></TwicImg>
        <span>class
          <span class="twic-code">landscape</span>
        </span>
      </div>
      <div class="twic-item square">
        <TwicImg src={ imgUrl }></TwicImg>
        <span>class
          <span class="twic-code">square</span>
        </span>
      </div>
      <div class="twic-item portrait">
        <TwicImg src={ imgUrl }></TwicImg>
        <span>class
          <span class="twic-code">portrait</span>
        </span>
      </div>
    </div>
    <h2>
      2. Class combination: <span class="twic-code">object-fit</span> and
      <span class="twic-code"> position</span> with
      <span class="twic-code">--twic-mode</span> and
      <span class="twic-code"> twic-position</span>
    </h2>
    <div class="twic-grid">
      <div class="twic-item contain left">
        <TwicImg src={ imgUrl } ratio="16/9"></TwicImg>
        <span>class
          <span class="twic-code">contain</span>
          & class
          <span class="twic-code">left</span>
        </span>
      </div>
      <div class="twic-item contain right">
        <TwicImg src={ imgUrl } ratio="16/9"></TwicImg>
        <span>class
          <span class="twic-code">contain</span>
          & class 
          <span class="twic-code">right</span>
        </span>
      </div>
      <div class="twic-item cover">
        <TwicImg src={ imgUrl } focus="50px100p" ratio="16/9"></TwicImg>
        <span>class 
          <span class="twic-code">cover</span>
        </span>
      </div>
    </div>
    <h2>
      3. Other classical settings (here with
      <span class="twic-code">width</span>)
    </h2>
    <div class="twic-grid">
      <div class="twic-item lg">
        <TwicImg src={ imgUrl }></TwicImg>
        <span>class 
          <span class="twic-code">lg</span>
        </span>
      </div>
      <div class="twic-item md">
        <TwicImg src={ imgUrl }></TwicImg>
        <span>class
          <span class="twic-code">md</span>
        </span>
      </div>
      <div class="twic-item sm">
        <TwicImg src={ imgUrl }></TwicImg>
        <span>class
          <span class="twic-code">sm</span>
        </span>
      </div>
    </div>
  </div>
</TwicWrapper>

<style lang="scss">
.twic-style-driven-container {
  h2 {
    margin-bottom: 30px;
  }

  .twic-grid {
    margin-bottom: 60px;
  }

  :global(.twic-item .twic-w) {
    background-color: #00ffa3;
    display: block;
  }

  .landscape {
    --twic-ratio: calc(4 / 3);
  }
  .portrait {
    --twic-ratio: calc(3 / 4);
  }
  .square {
    --twic-ratio: calc(1);
  }

  .contain {
    --twic-mode: contain;
  }

  .cover {
    --twic-mode: cover;
  }

  .left {
    --twic-position: left;
  }

  .right {
    --twic-position: right;
  }

  .lg {
    width: 300px;
  }

  .md {
    width: 150px;
  }

  .sm {
    width: 100px;
  }
}
</style>

// samples/next/pages/twicStyleDriven/index.jsx
/* eslint-disable react/no-unescaped-entities */
import React from "react";
import styles from "./index.module.scss";
import { TwicWrapper, TwicAbstract } from "@twicpics/components-demo-wrapper/react";
import { TwicImg } from "@twicpics/components/react";

const imgUrl = `components/horse.jpg`;

/**
 * demonstrates how you can set up components using pure CSS and the power of CSS variables.
 */
const TwicStyleDriven = () => (
    <TwicWrapper
    >
        <div className={ styles[ `twic-style-driven-container` ] }>
            <TwicAbstract
                title="CSS style driven"
                codeSandUrl="https://codesandbox.io/s/twicpics-x-next-style-driven-oe5bzn"
                codeSandBoxName="TwicPics x Next - Style Driven"
            >
                <p>
                    You can set up the TwicPics components using pure CSS and the power of CSS variables.
                </p>
            </TwicAbstract>
            <h2>
                1. Display ratio with <span className="twic-code">--twic-ratio</span>
            </h2>
            <div className="twic-grid">
                <div className={ `${ styles.landscape } twic-item` }>
                    <TwicImg src={imgUrl}></TwicImg>
                    <span>class landscape</span>
                </div>
                <div className={ ` ${ styles.square } twic-item` }>
                    <TwicImg src={imgUrl}></TwicImg>
                    <span>class square</span>
                </div>
                <div className={ ` ${ styles.portrait } twic-item` }>
                    <TwicImg src={imgUrl}></TwicImg>
                    <span>class portrait</span>
                </div>
            </div>
            <h2>
                2. Class combination: <span className="twic-code">object-fit</span> and <span className="twic-code">
                    position</span> with <span className="twic-code">--twic-mode</span> and <span className="twic-code">
                    twic-position</span>
            </h2>
            <div className="twic-grid">
                <div className={ `${ styles.contain } ${ styles.left } twic-item` }>
                    <TwicImg src={imgUrl} ratio="16/9"></TwicImg>
                    <span>class contain + class left</span>
                </div>
                <div className={ `${ styles.contain } ${ styles.right } twic-item` }>
                    <TwicImg src={imgUrl} ratio="16/9"></TwicImg>
                    <span>class contain + class right</span>
                </div>
                <div className={ `${ styles.cover } twic-item` }>
                    <TwicImg src={imgUrl} focus="50px100p" ratio="16/9"></TwicImg>
                    <span>class cover</span>
                </div>
            </div>
            <h2>3. Other classical settings (here with <span className="twic-code">width</span>)</h2>
            <div className="twic-grid">
                <div className={ `${ styles.lg } twic-item` }>
                    <TwicImg src={imgUrl}></TwicImg>
                    <span>class lg</span>
                </div>
                <div className={ `${ styles.md } twic-item` }>
                    <TwicImg src={imgUrl}></TwicImg>
                    <span>class md</span>
                </div>
                <div className={ `${ styles.sm } twic-item` }>
                    <TwicImg src={imgUrl}></TwicImg>
                    <span>class sm</span>
                </div>
            </div>
        </div>
    </TwicWrapper>
);

export default TwicStyleDriven;
