// samples/vue/src/components/TwicPosition.vue
<template>
  <TwicWrapper>
    <div class="twic-position-container">
      <TwicAbstract
        title="position property"
        codeSandBoxUrl="https://codesandbox.io/s/twicpics-x-vue2-position-property-bqwcdn"
        codeSandBoxName="TwicPics x Vue - Position property"
      >
        <p>
          In <span class="twic-code">contain</span> mode,
          <strong>
            the <dfn title="position property">position</dfn> property
            changes the location of the image inside the area of the component.
          </strong>
        </p>
        <p>
          The syntax is the same as for CSS position properties (e.g.
          <span class="twic-code"> background-position</span> or
          <span class="twic-code"> object-position</span>).
        </p>
        <p>
          Useful values are <span class="twic-code"> top</span>,
          <span class="twic-code"> bottom</span>,
          <span class="twic-code"> left</span>, and
          <span class="twic-code"> right</span>, but all valid CSS position
          values are valid.
        </p>
      </TwicAbstract>
      <div class="twic-testing-container">
        <button class="twic-button" v-on:click="onChangePosition">
          Click to change the position
        </button>
      </div>
      <div class="twic-grid">
        <div class="twic-item">
          <TwicImg
            :src="landscapeImgUrl"
            mode="contain"
            placeholder="none"
            :position="verticalPositionArray[verticalPositionIndex]"
          >
          </TwicImg>
          <span>
            <span class="twic-code">position="{{ verticalPositionArray[verticalPositionIndex] }}"</span>
          </span>
        </div>
        <div class="twic-item">
          <TwicImg
            :src="portraitImgUrl"
            mode="contain"
            placeholder="none"
            :position="horizontalPositionArray[horizontalPositionIndex]"
          >
          </TwicImg>
          <span>
            <span class="twic-code">position="{{ horizontalPositionArray[horizontalPositionIndex] }}"</span>
          </span
          >
        </div>
        <div class="twic-item">
          <TwicImg :src="landscapeImgUrl" mode="contain" placeholder="none">
          </TwicImg>
          <span>No position set (<span class="twic-code"> center</span> by default)</span>
        </div>
        <div class="twic-item">
          <TwicImg :src="portraitImgUrl" mode="contain" placeholder="none">
          </TwicImg>
          <span>No position set (<span class="twic-code"> center</span> by default)</span>
        </div>
      </div>
    </div>
  </TwicWrapper>
</template>

<script>
import {
  TwicAbstract,
  TwicWrapper,
} from "@twicpics/components-demo-wrapper/vue";

export default {
  name: "TwicPosition",
  components: {
    TwicAbstract,
    TwicWrapper,
  },
  data() {
    return {
      landscapeImgUrl: `components/position/horse.jpg`,
      portraitImgUrl: `components/position/forest.jpg`,
      horizontalPositionArray: [`left`, `right`, `center`],
      horizontalPositionIndex: 0,
      verticalPositionArray: [`top`, `bottom`, `center`],
      verticalPositionIndex: 0,
    };
  },
  methods: {
    onChangePosition() {
      this.horizontalPositionIndex =
        (this.horizontalPositionIndex + 1) %
        this.horizontalPositionArray.length;
      this.verticalPositionIndex =
        (this.verticalPositionIndex + 1) % this.verticalPositionArray.length;
    },
  },
};
</script>

<style lang="scss">
.twic-position-container {
  .twic-item .twic-w {
    background-color: #00ffa3;
    display: block;
  }
}
</style>

// samples/react/src/components/twicPosition/index.jsx
import React, { useState } from "react";
import { TwicWrapper, TwicAbstract } from "@twicpics/components-demo-wrapper/react";
import { TwicImg } from "@twicpics/components/react";
import "./index.scss";

const landscapeImgUrl = `components/position/horse.jpg`;
const portraitImgUrl = `components/position/forest.jpg`;
const verticalPositionArray = [ `top`, `bottom`, `center` ];
const horizontalPositionArray = [ `left`, `right`, `center` ];

/**
 * demonstrates position features (contain or cover)
 */
const TwicPosition = () => {

    // in this sample we are going to change position on a button click
    // --> we need state local management
    const [
        horizontalPositionIndex,
        setHorizontalPositionIndex,
    ] = useState( 0 );
    const [
        verticalPositionIndex,
        setVerticalPositionIndex,
    ] = useState( 0 );

    // user wants to change position
    const changePosition = () => {
        setHorizontalPositionIndex( ( horizontalPositionIndex + 1 ) % horizontalPositionArray.length );
        setVerticalPositionIndex( ( verticalPositionIndex + 1 ) % verticalPositionArray.length );
    };

    return (
        <TwicWrapper>
            <div className="twic-position-container">
                <TwicAbstract
                    title="position property"
                    codeSandUrl="https://codesandbox.io/s/twicpics-x-react-position-ymjxgg"
                    codeSandBoxName="TwicPics x React - Position"
                >
                    <p>
                      In <span className="twic-code">contain</span> mode,{" "}
                      <strong>
                        the <dfn title="position property">position</dfn> property
                        changes the location of the image inside the area of the component.
                      </strong>
                    </p>
                    <p>
                      The syntax is the same as for CSS position properties (e.g.{" "}
                      <span className="twic-code"> background-position</span> or{" "}
                      <span className="twic-code"> object-position</span>).
                    </p>
                    <p>
                      Useful values are <span className="twic-code"> top</span>,{" "}
                      <span className="twic-code"> bottom</span>,{" "}
                      <span className="twic-code"> left</span>, and{" "}
                      <span className="twic-code"> right</span> but all valid CSS position
                      values are valid.
                    </p>
                </TwicAbstract>
                <div className="twic-testing-container">
                    <button className="twic-button" onClick={changePosition}>Click to change position</button>
                </div>
                <div className="twic-grid">
                    <div className="twic-item">
                        <TwicImg
                            src={ `${ landscapeImgUrl }`}
                            mode="contain"
                            position={ verticalPositionArray[ verticalPositionIndex ] }
                        >
                        </TwicImg>
                        <span>
                          <span className="twic-code">position="{ verticalPositionArray[verticalPositionIndex] }"</span>
                        </span>
                    </div>
                    <div className="twic-item">
                        <TwicImg
                            src={ `${ portraitImgUrl }`}
                            mode="contain"
                            position={ horizontalPositionArray[ horizontalPositionIndex ] }
                        >
                        </TwicImg>
                        <span>
                          <span className="twic-code">position="{ horizontalPositionArray[horizontalPositionIndex] }"</span>
                        </span>
                    </div>
                    <div className="twic-item">
                        <TwicImg
                            src={ `${ landscapeImgUrl }`}
                            mode="contain"
                        >
                        </TwicImg>
                        <span>No position set (<span className="twic-code"> center</span> by default)</span>
                    </div>
                    <div className="twic-item">
                        <TwicImg
                            src={ `${ portraitImgUrl }`}
                            mode="contain"
                        >
                        </TwicImg>
                        <span>No position set (<span className="twic-code"> center</span> by default)</span>
                    </div>
                </div>
            </div>
        </TwicWrapper>
    );
};

export default TwicPosition;
