// samples/angular/src/app/twic-slider/twic-slider.component.ts
import { Component, OnInit } from "@angular/core";

@Component({
  selector: "app-twic-slider",
  templateUrl: "./twic-slider.component.html",
  styleUrls: ["./twic-slider.component.scss"],
})
export class TwicSliderComponent implements OnInit {
  // list of images to display in the slider
  images = [
    {
      url: `components/slider/pantone.jpg`,
    },
    {
      url: `components/slider/coffee.jpg`,
    },
    {
      url: `components/slider/reading.jpg`,
    },
    {
      url: `components/slider/cat-2.jpg`,
    },
    {
      url: `components/slider/mirror.jpg`,
    },
    {
      url: `components/slider/books.jpg`,
    },
    {
      url: `components/slider/sea.jpg`,
    },
    {
      url: `components/slider/frames.jpg`,
    },
    {
      url: `components/slider/dried-flower.jpg`,
    },
    {
      url: `components/slider/dune.jpg`,
    },
    {
      url: `components/slider/coffee-2.jpg`,
    },
    {
      url: `components/slider/yak.jpg`,
    },
    {
      url: `components/slider/dried-flower-2.jpg`,
    },
    {
      url: `components/slider/guitar.jpg`,
    },
    {
      url: `components/slider/field.jpg`,
    },
    {
      url: `components/slider/woman-and-sand.jpg`,
    },
  ];

  constructor() {}

  ngOnInit(): void {}
}

<!-- displays images with a horizontal scroll bar -->
<TwicWrapper>
  <TwicAbstract title="A slider" codeSandBoxUrl="" codeSandBoxName="TwicPics x Angular - Slider use case">
    <p>
      A simple slider that uses TwicPics for automatic lazy-loading,
      CLS optimization and art direction adaptation.
    </p>
    <p>
      <strong>Change the width of your browser</strong> to see the image ratio adapt according to the CSS rules.
    </p>
  </TwicAbstract>
  <div class="twic-slider-container">
    <ul class="slider">
      <li class="slider-item" *ngFor="let img of images">
        <figure class="card twic-item">
          <TwicImg [src]="img.url"></TwicImg>
        </figure>
      </li>
    </ul>
  </div>
</TwicWrapper>

// samples/react/src/components/twicSlider/index.jsx
import React from "react";
import { TwicWrapper, TwicAbstract } from "@twicpics/components-demo-wrapper/react";
import { TwicImg } from "@twicpics/components/react";
import "./index.scss";

/**
 * list of images to display in slider
 */
const images = [
    {
        "url": `components/slider/pantone.jpg`,
    },
    {
        "url": `components/slider/coffee.jpg`,
    },
    {
        "url": `components/slider/reading.jpg`,
    },
    {
        "url": `components/slider/cat-2.jpg`,
    },
    {
        "url": `components/slider/mirror.jpg`,
    },
    {
        "url": `components/slider/books.jpg`,
    },
    {
        "url": `components/slider/sea.jpg`,
    },
    {
        "url": `components/slider/frames.jpg`,
    },
    {
        "url": `components/slider/dried-flower.jpg`,
    },
    {
        "url": `components/slider/dune.jpg`,
    },
    {
        "url": `components/slider/coffee-2.jpg`,
    },
    {
        "url": `components/slider/yak.jpg`,
    },
    {
        "url": `components/slider/dried-flower-2.jpg`,
    },
    {
        "url": `components/slider/guitar.jpg`,
    },
    {
        "url": `components/slider/field.jpg`,
    },
    {
        "url": `components/slider/woman-and-sand.jpg`,
    },
];

/**
 * displays images with a horizontal scroll bar
 */
const TwicSlider = () => (
    <TwicWrapper>
        <TwicAbstract
            title="A slider"
            codeSandUrl="https://codesandbox.io/s/twicpics-x-react-responsive-image-slider-leulp"
            codeSandBoxName="TwicPics x React - Slider"
        >
            <p>
                A simple slider that uses TwicPics for automatic lazy-loading,
                CLS optimization and art direction adaptation.
            </p>
            <p>
                <strong>Change the width of your browser</strong> to see the image ratio adapt according to
                    the CSS rules.
            </p>
        </TwicAbstract>
        <div className="twic-slider-container">
            <ul className="slider">
                { images.map( ( image, i ) => (
                    <li className="slider-item" key={i}>
                        <figure className="card twic-item">
                            <TwicImg src={image.url}></TwicImg>
                        </figure>
                    </li>
                ) ) }
            </ul>
        </div>
    </TwicWrapper>
);

export default TwicSlider;
