// src/angular/projects/demo-wrapper/src/lib/twic-abstract/twic-abstract.component.ts
import { Component,Input, OnInit } from '@angular/core';

@Component({
    selector: 'TwicAbstract',
    templateUrl: './twic-abstract.component.html',
    styleUrls: ['./twic-abstract.component.css']
})
export class TwicAbstractComponent implements OnInit {

    @Input() title=``;
    @Input() codeSandBoxName?:string;
    @Input() codeSandBoxUrl?:string;

    constructor() { }

    ngOnInit(): void {
    }

}

<div class="twic-abstract">
    <h1>
        {{ title }}
    </h1>
    <div>
        <div>
            <ng-content></ng-content>
        </div>
        <ng-template [ngIf]="codeSandBoxUrl">
            <div class="codesandbox-container">
                <a
                    href="{{ codeSandBoxUrl }}?fontsize=14&hidenavigation=1&theme=dark">
                    <img src="https://codesandbox.io/static/img/play-codesandbox.svg"/>
                </a>
            </div>
        </ng-template>
    </div>
</div>

// src/svelte/TwicAbstract.svelte
<script>
  export let title;
  export let codeSandBoxName = ``;
  export let codeSandBoxUrl = ``;

  const alt = codeSandBoxName ? ` Edit ${ codeSandBoxName } ` : ` Edit on CodeSandbox`;
  const href = `${ codeSandBoxUrl }?fontsize=14&hidenavigation=1&theme=dark`;
</script>

<div class="twic-abstract">
  <h1>{ title }</h1>
  <div>
    <div>
      <slot></slot>
    </div>

    {#if codeSandBoxUrl}
      <div class="codesandbox-container">
        <a href={href}>
          <img
            src="https://codesandbox.io/static/img/play-codesandbox.svg"
            alt={alt}
          />
        </a>
      </div>
    {/if}
  </div>
</div>
