// src/react/twicWrapper.jsx
/* eslint-disable react/prop-types */
import { default as TwicHeader } from "./twicHeader";

import React from "react";

const TwicWrapper = ( { redirect, children, tags } ) => (
    <div id="twic-demo-wrapper">
        <TwicHeader redirect={redirect} tags={tags} ></TwicHeader>
        <main id="twic-demo-container">
            { children }
        </main>
    </div>
);

export default TwicWrapper;

// src/svelte/TwicWrapper.svelte
<script>
  import { default as TwicHeader } from "./TwicHeader.svelte";
  export let tags = [`@twicpics-components`];
  export let framework = `svelte`;
</script>

<div id="twic-demo-wrapper" class="">
  <TwicHeader tags={tags} framework={framework} />
  <main id="twic-demo-container">
    <slot></slot>
  </main>
</div>
