// src/svelte/TwicWrapper.svelte
<script>
  import { default as TwicHeader } from "./TwicHeader.svelte";
  export let tags = [`@twicpics-components`];
  export let framework = `svelte`;
</script>

<div id="twic-demo-wrapper" class="">
  <TwicHeader tags={tags} framework={framework} />
  <main id="twic-demo-container">
    <slot></slot>
  </main>
</div>

// wrapper/react/twicWrapper.jsx
import { default as TwicHeader } from "./twicHeader";

import React from "react";

const TwicWrapper = ( { redirect, children, tags } ) => {
    return (
        <div className="twic-demo">
            <TwicHeader redirect={redirect} tags={tags} ></TwicHeader>
            <main className="twic-demo-container">
                    {children}
            </main>
        </div>
    );
}

export default TwicWrapper;
