// samples/nuxt/pages/style-driven.vue
<template>
  <TwicWrapper framework="nuxt">
    <div class="twic-style-driven-container">
      <TwicAbstract
        title="CSS style driven"
        codeSandBoxUrl="https://codesandbox.io/s/twicpics-x-nuxt-style-driven-zw61ry"
        codeSandBoxName="TwicPics x Nuxt - CSS style driven"
      >
        <p>
          You can set up the TwicPics components using pure CSS and the power of
          CSS variables.
        </p>
      </TwicAbstract>
      <h2>1. Display ratio with <span class="twic-code">--twic-ratio</span></h2>
      <div class="twic-grid">
        <div class="twic-item landscape">
          <TwicImg :src="imgUrl"></TwicImg>
          <span>class
            <span class="twic-code">landscape</span>
          </span>
        </div>
        <div class="twic-item square">
          <TwicImg :src="imgUrl"></TwicImg>
          <span>class
            <span class="twic-code">square</span>
          </span>
        </div>
        <div class="twic-item portrait">
          <TwicImg :src="imgUrl"></TwicImg>
          <span>class
            <span class="twic-code">portrait</span>
          </span>
        </div>
      </div>
      <h2>
        2. Class combination: <span class="twic-code">object-fit</span> and
        <span class="twic-code"> position</span> with
        <span class="twic-code">--twic-mode</span> and
        <span class="twic-code"> twic-position</span>
      </h2>
      <div class="twic-grid">
        <div class="twic-item contain left">
          <TwicImg :src="imgUrl" ratio="16/9"></TwicImg>
          <span>class
            <span class="twic-code">contain</span>
            & class
            <span class="twic-code">left</span>
          </span>
        </div>
        <div class="twic-item contain right">
          <TwicImg :src="imgUrl" ratio="16/9"></TwicImg>
          <span>class
            <span class="twic-code">contain</span>
            & class 
            <span class="twic-code">right</span>
          </span>
        </div>
        <div class="twic-item cover">
          <TwicImg :src="imgUrl" focus="50px100p" ratio="16/9"></TwicImg>
          <span>class 
            <span class="twic-code">cover</span>
          </span>
        </div>
      </div>
      <h2>
        3. Other classical settings (here with
        <span class="twic-code">width</span>)
      </h2>
      <div class="twic-grid">
        <div class="twic-item lg">
          <TwicImg :src="imgUrl"></TwicImg>
          <span>class 
            <span class="twic-code">lg</span>
          </span>
        </div>
        <div class="twic-item md">
          <TwicImg :src="imgUrl"></TwicImg>
          <span>class
            <span class="twic-code">md</span>
          </span>
        </div>
        <div class="twic-item sm">
          <TwicImg :src="imgUrl"></TwicImg>
          <span>class
            <span class="twic-code">sm</span>
          </span>
        </div>
      </div>
    </div>
  </TwicWrapper>
</template>

<script>
import {
  TwicAbstract,
  TwicWrapper,
} from "@twicpics/components-demo-wrapper/vue";

export default {
  name: "TwicStyleDriven",
  components: {
    TwicAbstract,
    TwicWrapper,
  },
  data() {
    return {
      imgUrl: `components/horse.jpg`,
    };
  },
};
</script>

<style lang="scss">
.twic-style-driven-container {
  h2 {
    margin-bottom: 30px;
  }

  .twic-grid {
    margin-bottom: 60px;
  }

  .twic-item .twic-w {
    background-color: #00ffa3;
    display: block;
  }

  .landscape {
    --twic-ratio: calc(4 / 3);
  }
  .portrait {
    --twic-ratio: calc(3 / 4);
  }
  .square {
    --twic-ratio: calc(1);
  }

  .contain {
    --twic-mode: contain;
  }

  .cover {
    --twic-mode: cover;
  }

  .left {
    --twic-position: left;
  }

  .right {
    --twic-position: right;
  }

  .lg {
    width: 300px;
  }

  .md {
    width: 150px;
  }

  .sm {
    width: 100px;
  }
}
</style>

// samples/gatsby/src/pages/style-driven/index.jsx
/* eslint-disable react/no-unescaped-entities */
import React from "react";
import { TwicWrapper, TwicAbstract } from "@twicpics/components-demo-wrapper/react";
import { TwicImg } from "@twicpics/components/react";
import { twicStyleDrivenContainer,
    landscape,
    square,
    portrait,
    contain,
    left,
    right,
    cover,
    lg,
    sm,
    md } from "./index.module.scss";

const imgUrl = `components/horse.jpg`;

/**
 * demonstrates how you can set up components using pure CSS and the power of CSS variables.
 */
const TwicStyleDriven = () => (
    <TwicWrapper framework="gatsby">
        <div className={ twicStyleDrivenContainer }>
            <TwicAbstract
                title="CSS style driven"
                codeSandUrl="https://codesandbox.io/s/twicpics-x-gatsby-style-driven-h97h50"
                codeSandBoxName="TwicPics x Gatsby - Style driven"
            >
                <p>
                    You can set up the TwicPics components using pure CSS and the power of CSS variables.
                </p>
            </TwicAbstract>
            <h2>
                1. Display ratio with <span className="twic-code">--twic-ratio</span>
            </h2>
            <div className="twic-grid">
                <div className={ `${ landscape } twic-item` }>
                    <TwicImg src={imgUrl}></TwicImg>
                    <span>class{" "}
                      <span className="twic-code">landscape</span>
                    </span>
                </div>
                <div className={ ` ${ square } twic-item` }>
                    <TwicImg src={imgUrl}></TwicImg>
                    <span>class{" "}
                      <span className="twic-code">square</span>
                    </span>
                </div>
                <div className={ ` ${ portrait } twic-item` }>
                    <TwicImg src={imgUrl}></TwicImg>
                    <span>class{" "}
                      <span className="twic-code">portrait</span>
                    </span>
                </div>
            </div>
            <h2>
                2. Class combination: <span className="twic-code">object-fit</span> and <span className="twic-code">
                    position</span> with <span className="twic-code">--twic-mode</span> and <span className="twic-code">
                    twic-position</span>
            </h2>
            <div className="twic-grid">
                <div className={ `${ contain } ${ left } twic-item` }>
                    <TwicImg src={imgUrl} ratio="16/9"></TwicImg>
                    <span>class{" "}
                      <span className="twic-code">contain</span>{" "}
                      & class{" "}
                        <span className="twic-code">left</span>
                    </span>
                </div>
                <div className={ `${ contain } ${ right } twic-item` }>
                    <TwicImg src={imgUrl} ratio="16/9"></TwicImg>
                    <span>class{" "}
                      <span className="twic-code">contain</span>{" "}
                      & class{" "}
                        <span className="twic-code">right</span>
                    </span>
                </div>
                <div className={ `${ cover } twic-item` }>
                    <TwicImg src={imgUrl} focus="50px100p" ratio="16/9"></TwicImg>
                    <span>class{" "}
                       <span className="twic-code">cover</span>
                    </span>
                </div>
            </div>
            <h2>3. Other classical settings (here with <span className="twic-code">width</span>)</h2>
            <div className="twic-grid">
                <div className={ `${ lg } twic-item` }>
                    <TwicImg src={imgUrl}></TwicImg>
                    <span>class{" "}
                      <span className="twic-code">lg</span>
                    </span>
                </div>
                <div className={ `${ md } twic-item` }>
                    <TwicImg src={imgUrl}></TwicImg>
                    <span>class{" "}
                      <span className="twic-code">md</span>
                    </span>
                </div>
                <div className={ `${ sm } twic-item` }>
                    <TwicImg src={imgUrl}></TwicImg>
                    <span>class{" "}
                      <span className="twic-code">sm</span>
                    </span>
                </div>
            </div>
        </div>
    </TwicWrapper>
);

export default TwicStyleDriven;
