// samples/vue/src/components/twic-slideshow/TwicSlideshow.vue
<template>
  <!-- displays a carousel of responsive images -->
  <TwicWrapper>
    <div class="twic-slideshow-container">
      <TwicAbstract
        title="A Picture Carousel"
        codeSandBoxUrl="https://codesandbox.io/s/twicpics-x-vue2-carousel-5zhu43"
        codeSandBoxName="TwicPics x Vue - Picture Carousel"
      >
        <p>
          Use TwicPics for automatic lazy-loading, CLS optimization and art
          direction adaptation.
        </p>
        <p>
          <strong>Change the width of your browser</strong> to see the image
          ratio adapt according to the CSS rules.
        </p>
      </TwicAbstract>
      <Slideshow :images="images"></Slideshow>
    </div>
  </TwicWrapper>
</template>

<script>
import Slideshow from "./Slideshow.vue";
import {
  TwicAbstract,
  TwicWrapper,
} from "@twicpics/components-demo-wrapper/vue";

export default {
  name: "TwicSlideshow",
  components: {
    Slideshow,
    TwicAbstract,
    TwicWrapper,
  },
  data() {
    return {
      images: [
        {
          url: `components/slideshow/space-1.jpg`,
          focus: ``,
        },
        {
          url: `components/slideshow/space-2.jpg`,
          focus: `50px100p`,
        },
        {
          url: `components/slideshow/space-3.jpg`,
          focus: `50px100p`,
        },
        {
          url: `components/slideshow/space-4.jpg`,
          focus: `50px100p`,
        },
        {
          url: `components/slideshow/space-5.jpg`,
          focus: `50px100p`,
        },
      ],
    };
  },
};
</script>

<style lang="scss">
.twic-slideshow-container {
  margin: auto;
  width: 75%;
}
</style>

// samples/react/src/components/twicSlideshow/index.jsx
import './index.scss';
import React from "react";
import Slideshow, { SlideshowItem } from "./slideshow";
import { TwicWrapper, TwicAbstract } from "@twicpics/components-demo-wrapper/react";
import { TwicImg } from "@twicpics/components/react";

/**
 * images list
 */
const images = [
    {
        "url": `components/slideshow/space-1.jpg`,
        "focus": ``,
    },
    {
        "url": `components/slideshow/space-2.jpg`,
        "focus": `50px100p`,
    },
    {
        "url": `components/slideshow/space-3.jpg`,
        "focus": `50px100p`,
    },
    {
        "url": `components/slideshow/space-4.jpg`,
        "focus": `50px100p`,
    },
    {
        "url": `components/slideshow/space-5.jpg`,
        "focus": `50px100p`,
    },
];

/**
 * displays a carousel of responsive images
 */
const TwicSlideshow = () => (
    <TwicWrapper>
        <div className="twic-slideshow-container">
            <TwicAbstract
                title="A Picture Carousel"
                codeSandUrl="https://codesandbox.io/s/twicpics-x-react-responsive-slideshow-y23mt"
                codeSandBoxName="TwicPics x React - Picture Carousel"
            >
                <p>
                    Use TwicPics for automatic lazy-loading, CLS optimization and art direction adaptation.
                </p>
                <p>
                    <strong>Change the width of your browser</strong> to see the image ratio adapt according to
                    the CSS rules.
                </p>
            </TwicAbstract>
            <Slideshow>
                { images.map( ( image, i ) => (
                    <SlideshowItem key={ i }>
                        <TwicImg
                            className="twic-slideshow-responsive"
                            focus={ image.focus }
                            src={ image.url }
                        ></TwicImg>
                    </SlideshowItem>
                ) ) }
            </Slideshow>
        </div>
    </TwicWrapper>
);

export default TwicSlideshow;
