// src/angular/projects/demo-wrapper/src/lib/twic-wrapper/twic-wrapper.component.ts
import { Component, Input, OnInit } from "@angular/core";

@Component({
  selector: "TwicWrapper",
  templateUrl: "./twic-wrapper.component.html",
  styleUrls: ["./twic-wrapper.component.css"],
})
export class TwicWrapperComponent implements OnInit {
  @Input() tags = [`@twicpics-components`];
  @Input()
  redirect = `https://github.com/TwicPics/components/blob/main/documentation/angular.md`;

  constructor() {}

  ngOnInit(): void {}
}

<div id="twic-demo-wrapper" class="todo">
    <TwicHeader [tags]="tags" [redirect]="redirect"></TwicHeader>
    <main id="twic-demo-container">
        <ng-content></ng-content>
    </main>
</div>

// src/vue/twicWrapper.vue
<template>
  <div id="twic-demo-wrapper" class="">
    <TwicHeader :tags="tags" :redirect="redirect" :framework="framework" />
    <main id="twic-demo-container">
      <slot></slot>
    </main>
  </div>
</template>

<script>
import { default as TwicHeader } from "./twicHeader";
export default {
  name: "TwicWrapper",
  components: {
    TwicHeader,
  },
  props: {
    tags: {
      type: Array,
      default() {
        return [`@twicpics-components`];
      },
      required: false,
    },
    redirect: {
      type: String,
      default: `https://github.com/TwicPics/components/blob/0.6.3/documentation/vue2.md`,
      required: false,
    },
    framework: {
      type: String,
      default: `vue`,
      required: false,
    },
  },
};
</script>
