// samples/next/pages/art-directions/index.jsx
/* eslint-disable react/no-unescaped-entities */
import React from "react";
import styles from "./index.module.scss";
import { TwicWrapper, TwicAbstract } from "@twicpics/components-demo-wrapper/react";
import { TwicImg } from "@twicpics/components/react";

const imgUrl = `components/greece.jpg`;

/**
 * demonstrates that setting up components using CSS enables hassle-free responsive designs.
 */
const TwicArtDirections = () => (
    <TwicWrapper framework="next">
        <div className={ styles[ `twic-art-directions-container` ] }>
            <TwicAbstract
                title="Art directions with CSS media queries"
                codeSandUrl="https://codesandbox.io/s/twicpics-x-next-art-direction-ps2zj"
                codeSandBoxName="TwicPics x Next - Art Directions"
            >
                <p>Setting up components using CSS enables hassle-free responsive designs.</p>
                <p>You do not need to create a set of images derived from the original.</p>
                <p>
                    You only need to manage a master image in your template:
                    TwicPics understands your CSS and does the rest.
                </p>
                <p>
                    <strong>Change the width of your browser </strong>
                    to see the image ratio adapt according to the CSS rules.
                </p>
            </TwicAbstract>
            <div className={ `${ styles[ `style-driven-responsive` ] } twic-item }`}>
                <TwicImg src={imgUrl} className={ styles[ `style-driven-responsive` ] } focus="48px100p">
                </TwicImg>
            </div>
        </div>
    </TwicWrapper>
);

export default TwicArtDirections;

// samples/nuxt/pages/art-directions.vue
<!-- Please remove this file from your project -->
<template>
  <TwicWrapper framework="nuxt">
    <div class="twic-art-direction-container">
      <TwicAbstract
        title="Art directions with CSS media queries"
        codeSandBoxUrl="https://codesandbox.io/s/twicpics-x-nuxt-art-direction-ni4875"
        codeSandBoxName="TwicPics x Nuxt - Art directions"
      >
        <p>
          Setting up components using CSS enables hassle-free responsive
          designs.
        </p>
        <p>
          You do not need to create a set of images derived from the original.
        </p>
        <p>
          You only need to manage a master image in your template: TwicPics
          understands your CSS and does the rest.
        </p>
        <p>
          <strong>Change the width of your browser </strong>
          to see the image ratio adapt according to the CSS rules.
        </p>
      </TwicAbstract>
      <div class="twic-item style-driven-responsive">
        <TwicImg src="components/greece.jpg" focus="48px100p"></TwicImg>
      </div>
    </div>
  </TwicWrapper>
</template>

<script>
import {
  TwicAbstract,
  TwicWrapper,
} from "@twicpics/components-demo-wrapper/vue";

export default {
  name: "ArtDirectionsPage",
  components: {
    TwicAbstract,
    TwicWrapper,
  },
};
</script>

<style lang="scss">
.twic-art-direction-container {
  .style-driven-responsive {
    --twic-ratio: calc(2 / 3);
    --twic-mode: cover;
    margin: auto;
  }
}

.twic-art-direction-container .style-driven-responsive {
  max-width: 1024px;

  @media (min-width: 640px) {
    --twic-ratio: calc(1);
  }

  @media (min-width: 768px) {
    --twic-ratio: calc(4 / 3);
  }

  @media (min-width: 1024px) {
    --twic-ratio: calc(16 / 9);
  }

  @media (min-width: 1280px) {
    --twic-ratio: calc(1.85);
  }

  @media (min-width: 1536px) {
    --twic-ratio: calc(21 / 9);
  }
}
</style>
