// samples/next/pages/ratio/index.jsx
import React, { useState } from "react";
import { TwicWrapper, TwicAbstract } from "@twicpics/components-demo-wrapper/react";
import { TwicImg } from "@twicpics/components/react";
import styles from "./index.module.scss";

const imgUrl = `components/woman-and-winter.jpg`;
const ratioValues = [ `2.39`, `16/9`, `4/3`, null, `0.75` ];

/**
 * demonstrates the ratio property
 */
const TwicRatio = () => {
    const [ ratioIndex, setRatioIndex ] = useState( 0 );
    const [ fullWidthAera, setFullWidthAera ] = useState( true );

    const changeRatio = () => {
        setRatioIndex( ( ratioIndex + 1 ) % ratioValues.length );
    };

    const changeAeraWidth = () => {
        setFullWidthAera( !fullWidthAera );
    };

    return (
        <TwicWrapper framework="next">
            <div className={ styles[ `twic-ratio-container` ] }>
                <TwicAbstract
                    title="ratio property"
                    codeSandUrl="https://codesandbox.io/s/twicpics-x-next-ratio-feature-485wh8"
                    codeSandBoxName="TwicPics x Next - Ratio"
                >
                    <p>
                      The <span className="twic-code">ratio</span> property determines the value
                      of the width/height ratio of the image display area.
                    </p>
                    <p>Its value can be:</p>
                    <ul>
                      <li>
                        a ratio expression of the form width/height like{" "}
                        <span className="twic-code">4/3</span>,{" "}
                        <span className="twic-code">16/9</span>, or{" "}
                        <span className="twic-code">1/1</span>.
                      </li>
                      <li>
                        a number that is the result of such an expression like{" "}
                        <span className="twic-code">1.85</span>,{" "}
                        <span className="twic-code">2</span>, or{" "}
                        <span className="twic-code">0.5</span>.
                      </li>
                    </ul>
                    <p>
                      A square area (<span className="twic-code"> ratio="1"</span>) will be
                      created by default.
                    </p>
                </TwicAbstract>
                <div className="twic-testing-container">
                    <button className="twic-button" onClick={changeRatio}>Click to change ratio</button>
                    <button className="twic-button" onClick={changeAeraWidth}>Click to change area width</button>
                </div>
                <div className={`twic-grid ${fullWidthAera ? `full-width` : `half-width`} `}>
                    <div className="twic-item">
                      <TwicImg src={ imgUrl } ratio={ ratioValues[ratioIndex] }>
                      </TwicImg>
                      <span>
                        <span className="twic-code">ratio="{
                          ratioValues[ratioIndex] ? ratioValues[ratioIndex] : 1
                        }"</span>{" "}
                        { !ratioValues[ ratioIndex ] && "- default ratio"}{" "}
                        (mode is <span className="twic-code">cover</span>)
                      </span>
                    </div>
                    <div className="twic-item">
                        <TwicImg
                        src={ imgUrl }
                        mode="contain"
                        ratio={ ratioValues[ratioIndex] }
                        >
                        </TwicImg>
                        <span>
                          <span className="twic-code">ratio="{
                            ratioValues[ratioIndex] ? ratioValues[ratioIndex] : 1
                          }"</span>{" "}
                          { !ratioValues[ ratioIndex ] && "- default ratio"}{" "}
                          (mode is <span className="twic-code">contain</span>)
                        </span>
                    </div>
                </div>
            </div>
        </TwicWrapper>
    );
};

export default TwicRatio;

// samples/nuxt/pages/ratio.vue
<template>
  <!-- demonstrates the ratio property -->
  <TwicWrapper framework="nuxt">
    <div class="twic-ratio-container">
      <TwicAbstract
        title="ratio property"
        codeSandBoxUrl="https://codesandbox.io/s/twicpics-x-nuxt-ratio-property-1ruvjf"
        codeSandBoxName="TwicPics x Nuxt - Ratio property"
      >
        <p>
          The <span class="twic-code">ratio</span> property determines the value
          of the width/height ratio of the image display area.
        </p>
        <p>The value can be:</p>
        <ul>
          <li>
            a ratio expression of the form width/height like
            <span class="twic-code">4/3</span>,
            <span class="twic-code">16/9</span>, or
            <span class="twic-code">1/1</span> .
          </li>
          <li>
            a number that is the result of such an expression like
            <span class="twic-code">1.85</span>,
            <span class="twic-code">2</span>, or
            <span class="twic-code">0.5</span>.
          </li>
        </ul>
        <p>
          A square area (<span class="twic-code"> ratio="1"</span>) will be
          created by default.
        </p>
      </TwicAbstract>
      <div class="twic-testing-container">
        <button class="twic-button" v-on:click="onChangeRatio">
          Click to change the aspect-ratio
        </button>
        <button class="twic-button" v-on:click="onChangeAreaWidth">
          Click to change the area width
        </button>
      </div>
      <div
        class="twic-grid"
        v-bind:class="{
          'modal-opened': show,
          'half-width': fullWidthAera === false,
        }"
      >
        <div class="twic-item">
          <TwicImg v-if="show" :src="imgUrl" :ratio="ratioValues[ratioIndex]">
          </TwicImg>
          <span>
            ratio={{
              ratioValues[ratioIndex] ? ratioValues[ratioIndex] : "1 [default]"
            }}
            (cover)
          </span>
        </div>
        <div class="twic-item">
          <TwicImg
            v-if="show"
            :src="imgUrl"
            mode="contain"
            :ratio="ratioValues[ratioIndex]"
          >
          </TwicImg>
          <span>
            ratio={{
              ratioValues[ratioIndex] ? ratioValues[ratioIndex] : "1 [default]"
            }}
            (contain)
          </span>
        </div>
      </div>
    </div>
  </TwicWrapper>
</template>

<script>
import {
  TwicAbstract,
  TwicWrapper,
} from "@twicpics/components-demo-wrapper/vue";

export default {
  name: "TwicRatio",
  components: {
    TwicAbstract,
    TwicWrapper,
  },
  data() {
    return {
      imgUrl: `components/woman-and-winter.jpg`,
      ratioValues: [`2.39`, `16/9`, `4/3`, ``, `0.75`],
      ratioIndex: 0,
      fullWidthAera: true,
      // trick to force reload TwicImg
      show: true,
    };
  },
  methods: {
    onChangeRatio() {
      setTimeout(() => (this.show = false));
      this.ratioIndex = (this.ratioIndex + 1) % this.ratioValues.length;
      setTimeout(() => (this.show = true));
    },

    onChangeAreaWidth() {
      this.fullWidthAera = !this.fullWidthAera;
    },
  },
};
</script>

<style lang="scss">
.twic-ratio-container {
  .twic-grid {
    --twic-grid-columns-width: 40%;
    &.full-width {
      .twic-item {
        width: 100%;
      }
    }

    &.half-width {
      .twic-item {
        width: 50%;
        margin: auto;
      }
    }
  }

  .twic-item .twic-w {
    background-color: #00ffa3;
    display: block;
  }
}
</style>
