// samples/svelte/src/components/Home.svelte
<script>
import { TwicWrapper } from "@twicpics/components-demo-wrapper/svelte";
import { TwicImg } from "@twicpics/components/svelte3";

const categories = [
  {
    "title": `<TwicImg> use cases`,
    "items": [
        {
            "route": `/basic-grid`,
            "imgSrc": `https://assets.twicpics.com/examples/football.jpg`,
            "title": `Basic example`,
        },
        {
            "route": `/art-directions`,
            "imgSrc": `components/greece.jpg`,
            "title": `Art directions`,
        },
        {
            "route": `/flip-cards`,
            "imgSrc": `components/flip/orange-1.jpg`,
            "title": `Flip cards`,
        },
        {
            "route": `/grid-and-zoom`,
            "imgSrc": `components/portraits/woman-1.jpg`,
            "title": `Grid & Zoom`,
        },
        {
            "route": `/modal`,
            "imgSrc": `components/modal/seagull.jpg`,
            "title": `Modal`,
        },
        {
            "route": `/slider`,
            "imgSrc": `components/slider/pantone.jpg`,
            "title": `Slider`,
        },
        {
            "route": `/slideshow`,
            "imgSrc": `components/slideshow/space-1.jpg`,
            "title": `Slideshow`,
        },
        {
            "route": `/style-driven`,
            "imgSrc": `components/horse.jpg`,
            "title": `Style driven`,
        },
        {
            "route": `/working-without-images`,
            "imgSrc": `components/woman.jpg`,
            "title": `Working without images`,
        },
    ],
  },
  {
    "title": `<TwicImg> properties`,
    "items": [
        {
            "route": `/focus`,
            "imgSrc": `components/puppy.jpg`,
            "title": `focus`,
        },
        {
            "route": `/mode`,
            "imgSrc": `components/fox.jpg`,
            "title": `mode`,
        },
        {
            "route": `/placeholder`,
            "imgSrc": `components/cat.jpg`,
            "title": `placeholder`,
        },
        {
            "route": `/position`,
            "imgSrc": `components/position/horse.jpg`,
            "title": `position`,
        },
        {
            "route": `/pretransform`,
            "imgSrc": `components/man-hiding-his-hands.jpg`,
            "title": `preTransform`,
        },
        {
            "route": `/ratio`,
            "imgSrc": `components/woman-and-winter.jpg`,
            "title": `ratio`,
        },
        {
            "route": `/transition`,
            "imgSrc": `components/peacock.jpg`,
            "title": `transition`,
        },
    ],
  },
];
</script>

<TwicWrapper>
  <div class="home-container">
    {#each categories as category}
      <div class="twic-panel">
        <h3>{ category.title }</h3>
        <div class="twic-grid">
          {#each category.items as item}
            <a href={ item.route }>
              <figure class="twic-item">
                <TwicImg
                    src={ item.imgSrc }
                    focus="auto"
                    ratio="0.95">
                </TwicImg>
                <figcaption>
                  <p>{ item.title }</p>
                </figcaption>
              </figure>
            </a>
          {/each}
        </div>
      </div>
    {/each}
  </div>
</TwicWrapper>

<style lang="scss">
.home-container{
  h3 {
    margin-bottom: 1rem;
  }

  .twic-grid {
    --twic-grid-columns-width: calc(200px);
  }

  figure {
    position: relative;
    & figcaption {
      position: absolute;
      right: 0;
      bottom: 0;
      left: 0;
      display: flex;
      justify-content: center;
      align-items: center;
      margin: 12px;
      height: 32px;
      font-size: 1em;
      color: #fff;
      background: rgba(0, 0, 0, 0.5);
      transition: all 0.3s;
    }
    &:hover{
      cursor: pointer;
      & figcaption {
          bottom: 40%;
      }
    }
  }
}
</style>

// samples/react/src/components/_home/index.jsx
import React from "react";
import { TwicWrapper } from "@twicpics/components-demo-wrapper/react";
import { NavLink } from "react-router-dom";
import { TwicImg } from "@twicpics/components/react";
import "./index.scss";

const categories = [
    {
        "title": `<TwicImg> use cases`,
        "items": [
            {
                "route": `/basic-grid`,
                "imgSrc": `https://assets.twicpics.com/examples/football.jpg`,
                "title": `Basic example`,
            },
            {
                "route": `/art-direction`,
                "imgSrc": `components/greece.jpg`,
                "title": `Art direction`,
            },
            {
                "route": `/flip`,
                "imgSrc": `components/flip/orange-1.jpg`,
                "title": `Flip cards`,
            },
            {
                "route": `/life-cycle`,
                "imgSrc": `components/portraits/woman-1.jpg`,
                "title": `Life cycle`,
            },
            {
                "route": `/modal`,
                "imgSrc": `components/modal/seagull.jpg`,
                "title": `Modal`,
            },
            {
                "route": `/slider`,
                "imgSrc": `components/slider/pantone.jpg`,
                "title": `Slider`,
            },
            {
                "route": `/slideshow`,
                "imgSrc": `components/slideshow/space-1.jpg`,
                "title": `Slideshow`,
            },
            {
                "route": `/style-driven`,
                "imgSrc": `components/horse.jpg`,
                "title": `Style driven`,
            },
        ],
    },
    {
        "title": `<TwicImg> properties`,
        "items": [
            {
                "route": `/focus`,
                "imgSrc": `components/puppy.jpg`,
                "title": `focus`,
            },
            {
                "route": `/mode`,
                "imgSrc": `components/fox.jpg`,
                "title": `mode`,
            },
            {
                "route": `/placeholders`,
                "imgSrc": `components/cat.jpg`,
                "title": `placeholder`,
            },
            {
                "route": `/positions`,
                "imgSrc": `components/position/horse.jpg`,
                "title": `position`,
            },
            {
                "route": `/ratio`,
                "imgSrc": `components/woman-and-winter.jpg`,
                "title": `ratio`,
            },
            {
                "route": `/transition`,
                "imgSrc": `components/peacock.jpg`,
                "title": `transition`,
            },
        ],
    },
];

function Home() {
    return (
        <TwicWrapper>
            <div className="home-container">
                { categories.map( ( category, i ) => (
                    <div className="twic-panel" key={`category ${ i }`}>
                        <h3>{ category.title }</h3>
                        <div className="twic-grid">
                            { category.items.map( ( item, j ) => (
                                <NavLink to={ item.route } key={`useCase ${ j }`}>
                                    <figure className="twic-item">
                                        <TwicImg
                                            src={ item.imgSrc }
                                            focus="auto"
                                            ratio="0.95">
                                        </TwicImg>
                                        <figcaption>
                                            <p>{ item.title }</p>
                                        </figcaption>
                                    </figure>
                                </NavLink>
                            ) ) }
                        </div>
                    </div>
                ) )}
            </div>
        </TwicWrapper>
    );
}

export default Home;
