// src/vue/twicHeader.vue
<template>
  <header id="twic-header">
    <a href="/" title="Home">
      <h1 class="heading-primary">
        <img
          class="twicpics-logo"
          src="https://assets.twicpics.com/demo/@twicpics-components/logos/twicpics.svg"
          alt="TwicPics logo"
        />
        <span>x</span>
        <img :class="this.class" :src="this.src" :alt="this.alt" />
      </h1>
    </a>
    <div class="tags-container">
      <div v-for="tag in tags" :key="tag" class="tag">
        {{ tag }}
      </div>
      <a
        :href="redirect"
        target="_blank"
        class="documentation-link tag tag--bg-purple-rain"
        rel="noreferrer"
      >
        Documentation
      </a>
    </div>
  </header>
</template>

<script>
export default {
  name: "TwicHeader",
  props: {
    tags: {
      type: Array,
      required: true,
    },
    redirect: {
      type: String,
      required: true,
    },
    framework: {
      type: String,
      required: true,
    },
  },
  data() {
    return {
      LOGO_PATH: `https://assets.twicpics.com/demo/@twicpics-components/logos/`,
      class: ``,
      src: ``,
      alt: ``,
    };
  },

  created() {
    if (this.framework === `vue`) {
      this.class = `vue-logo`;
      this.src = `${this.LOGO_PATH}vue.png`;
      this.alt = `Vue logo`;
    } else if (this.framework === `nuxt`) {
      this.class = `nuxt-logo`;
      this.src = `${this.LOGO_PATH}nuxt-2.png`;
      this.alt = `Nuxt logo`;
    }
  },
};
</script>

// src/angular/projects/demo-wrapper/src/lib/twic-header/twic-header.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
    selector: 'TwicHeader',
    templateUrl: './twic-header.component.html',
    styleUrls: ['./twic-header.component.css']
})
export class TwicHeaderComponent implements OnInit {

    @Input() tags:any[];
    @Input() redirect:string;

    urlLogoTwicPics = `https://assets.twicpics.com/demo/@twicpics-components/logos/twicpics.svg`;
    urlLogoAngular = `https://assets.twicpics.com/demo/@twicpics-components/logos/angular.svg`;
    classLogoAngular = `angular-logo`;
    altLogoAngular = `Angular logo`;

    constructor() { }

    ngOnInit(): void {
    }

}

<header id="twic-header">
    <a href="/" title="Home">
        <h1 class="heading-primary">
            <img [src]="urlLogoTwicPics" class="twicpics-logo" alt="TwicPics logo" />
            <span>x</span>
            <img [src]="urlLogoAngular" [ngClass]="classLogoAngular" [alt]="altLogoAngular" />
        </h1>
    </a>
    <div class="tags-container">
        <ng-container *ngFor="let tag of tags">
            <div class="tag">
                {{ tag }}
            </div>
        </ng-container>
        <a [href]="redirect" target="_blank" class="documentation-link tag tag--bg-purple-rain" rel="noreferrer">
            Documentation
        </a>
    </div>
</header>
