// samples/react/src/components/twicSlideshow/slideshow/index.jsx
import React, { useEffect, useState } from "react";
import { useSwipeable } from "react-swipeable";

import "./index.scss";

const timerDuration = 3000;

export const SlideshowItem = ( { children, width } ) => (
    <div className="slideshow-item" style={ {
        width,
    } }>
        { children }
    </div>
);

const Slideshow = ( { children } ) => {
    const [ activeIndex, setActiveIndex ] = useState( 0 );
    const [ paused, setPaused ] = useState( false );

    const updateIndex = newIndex => {
        const nbElement = React.Children.count( children ) - 1;
        let _newIndex = newIndex;
        if ( newIndex < 0 ) {
            _newIndex = nbElement;
        } else if ( newIndex >= nbElement ) {
            _newIndex = 0;
        }
        setActiveIndex( _newIndex );
    };

    useEffect( () => {
        const interval = setInterval( () => {
            if ( !paused ) {
                updateIndex( activeIndex + 1 );
            }
        }, timerDuration );

        return () => {
            if ( interval ) {
                clearInterval( interval );
            }
        };
    } );

    const handlers = useSwipeable( {
        "onSwipedLeft": () => updateIndex( activeIndex + 1 ),
        "onSwipedRight": () => updateIndex( activeIndex - 1 ),
    } );

    return (
        <div className="slideshow-container">
            <button className="slick-prev slick-arrow" onClick={ () => {
                updateIndex( activeIndex - 1 );
            } }>&#8249;</button>
            <div className="twic-item">
                <div className="slideshow-inner-container">
                    <div className=""
                        {...handlers}
                        onMouseEnter={() => setPaused( true )}
                        onMouseLeave={() => setPaused( false )}
                    >
                        <div
                            className="inner"
                            style={{
                                // eslint-disable-next-line no-magic-numbers
                                "transform": `translateX(-${ activeIndex * 100 }%)`,
                            }}
                        >
                            {React.Children.map( children, child => React.cloneElement( child, {
                                "width": `100%`,
                            } ) )}
                        </div>
                    </div>
                </div>
            </div>
            <ul className="slick-dots">
                {React.Children.map( children, ( _child, index ) => (
                    <li className={`${ index === activeIndex ? `slick-active` : `` }`}>
                        <button onClick={ () => {
                            updateIndex( index );
                        } } ></button>
                    </li>
                ) )}
            </ul>
            <button className="slick-next slick-arrow" onClick={ () => {
                updateIndex( activeIndex + 1 );
            } }>&#8250;</button>
        </div>
    );
};

export default Slideshow;

// samples/angular/src/app/twic-slideshow/slideshow/slideshow.component.ts
import { Component, Input, OnInit, OnDestroy } from "@angular/core";

@Component({
    selector: "app-slideshow",
    templateUrl: "./slideshow.component.html",
    styleUrls: ["./slideshow.component.scss"],
})
export class SlideshowComponent implements OnInit, OnDestroy {
    @Input() images!: { url: string, focus: string }[];

    activeIndex = 0;
    isPaused = false;
    timerDuration = 3000;

    interval: any;

    constructor() { }

    ngOnInit(): void {
        this.interval = setInterval(() => {
            if (!this.isPaused) {
                this.updateIndex(this.activeIndex + 1);
            }
        }, this.timerDuration);
    }

    ngOnDestroy(): void {
        if (this.interval) {
            clearInterval(this.interval);
        }
    }

    updateIndex(newIndex: number) {
        const nbElement = this.images.length - 1;
        let _newIndex = newIndex;
        if (newIndex < 0) {
            _newIndex = nbElement;
        } else if (newIndex > nbElement) {
            _newIndex = 0;
        }
        this.activeIndex = _newIndex;
    }

    setIsPaused(): void {
        this.isPaused = !this.isPaused;
    }
}

<div class="slideshow-container">
  <button
    class="slick-prev slick-arrow"
    (click)="updateIndex( activeIndex - 1 )">
    &#8249;
  </button>
  <div class="twic-item">
    <div class="slideshow-inner-container">
      <div (mouseenter)="setIsPaused()" (mouseleave)="setIsPaused()">
        <div class="inner" [ngStyle]="{ transform: 'translateX(-' + (activeIndex * 100) + '%)' }">
            <div class="slideshow-item" *ngFor="let img of images">
                <TwicImg
                  class="twic-slideshow-responsive"
                  [src]="img.url"
                  [focus]="img.focus"
                ></TwicImg>
              </div>
        </div>
      </div>
    </div>
  </div>
  <ul class="slick-dots">
    <li *ngFor="let img of images; let imgIndex=index;" [ngClass]="{ 'slick-active': imgIndex === activeIndex }">
      <button (click)="updateIndex( imgIndex )"></button>
    </li>
  </ul>
  <button
    class="slick-next slick-arrow"
    (click)="updateIndex( activeIndex + 1 )">
    &#8250;
  </button>
</div>
