// samples/angular/src/app/app.component.ts
import { Component } from "@angular/core";
import { installTwicPics } from "@twicpics/components/angular13";

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss']
})
export class AppComponent {
    title = 'angular';
}

// TwicPics Components configuration (see Setup Options)
installTwicPics( {
    "domain": `https://demo.twic.pics`,
    "anticipation": 0.5,
    "step": 100,
} );

// samples/next/pages/_app.jsx
import React from "react";
import { installTwicPics } from "@twicpics/components/react";
import '@twicpics/components-demo-wrapper/style.css';
import "@twicpics/components/style.css";
import "./_app.css";

installTwicPics( {
    "domain": `https://demo.twic.pics`,
    "anticipation": 0.5,
    "step": 100,
} );

function MyApp( { Component, pageProps } ) {
    return <Component {...pageProps} />;
}

export default MyApp;
